''
'' A blue gray theme
''
'' Author: Brett Schwarz
'' Copyright (c) 2019 by Brett Schwarz

!$THEME = "blue-nexus"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false
skinparam actorStyle awesome

!$WHITE = "#fff"
!$BLACK = "#000"
!$GRAY = "#999"
!$PRIMARY = "#0C98D6"
!$SECONDARY = "#F5F5F5"
!$SUCCESS = "#51ADA1"
!$INFO = "#2396D6"
!$WARNING = "#F3BB00"
!$DANGER = "#E84927"
!$LIGHT = "#F1F1F1"
!$DARK = "#15395F"

!$FGCOLOR = $BLACK
!$PRIMARY_TEXT = $WHITE
!$SECONDARY_TEXT = $FGCOLOR
!$SECONDARY_BORDER = $GRAY

!$INFO_TEXT = $WHITE
!$SUCCESS_TEXT = $WHITE
!$WARNING_TEXT = $WHITE
!$DANGER_TEXT = $WHITE

!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

!procedure $primary_scheme()
	FontColor $PRIMARY_TEXT
	BackgroundColor $DARK
	BorderColor $DARK
!endprocedure

!procedure $outline_scheme()
	FontColor $DARK
	BackgroundColor $WHITE
	BorderColor $DARK
!endprocedure

!procedure $secondary_scheme()
	FontColor $SECONDARY_TEXT
	BorderColor $SECONDARY_BORDER
	BackgroundColor $SECONDARY
	BorderThickness 	         1
!endprocedure

''
'' Global Default Values
''
skinparam defaultFontName        "Segoe UI"
'skinparam defaultFontSize        14
skinparam DefaultFontColor       $DARK
'skinparam dpi                    100
skinparam shadowing              false
skinparam roundcorner            10
'skinparam BoxPadding             20
'skinparam Padding                4
skinparam stereotype {
    CBackgroundColor $SECONDARY_BORDER
    CBorderColor $SECONDARY_BORDER
    ABackgroundColor $SUCCESS
    ABorderColor $SUCCESS
    IBackgroundColor $DANGER
    IBorderColor $DANGER
    EBackgroundColor $WARNING
    EBorderColor $WARNING
    NBackgroundColor $INFO
    NBorderColor $DARK
}
skinparam title {
	$outline_scheme()
	FontSize	    	         14
	BorderRoundCorner            0
}


skinparam legend {
	BackgroundColor  #fff4d1
	BorderColor  $DARK
	FontColor $DARK
}

!startsub swimlane
skinparam swimlane {
	BorderColor $SECONDARY_BORDER
	BorderThickness 2
	TitleBackgroundColor  $SECONDARY
	TitleFontColor $SECONDARY_TEXT
}
!endsub

!startsub activity

skinparam activity {
	$primary_scheme()
	BarColor $DARK
	StartColor $DARK
	EndColor $DARK
	''
	DiamondBackgroundColor $SECONDARY
  	DiamondBorderColor $SECONDARY_BORDER
	DiamondFontColor $SECONDARY_TEXT
}
!endsub

!startsub arrow

skinparam arrow {
	Thickness 1
	Color $SECONDARY_BORDER
	FontColor $SECONDARY_TEXT
	Padding 1
	LineColor $SECONDARY_BORDER
}
!endsub

!startsub partition

skinparam partition {
	$secondary_scheme()
}
!endsub

!startsub sequence

skinparam sequence {
	BorderColor $PRIMARY
	' For some reason sequence title font color does not pick up from global
	TitleFontColor $PRIMARY
	BackgroundColor $BGCOLOR
	StartColor $DARK
	EndColor $DARK
	''
	BoxBackgroundColor $BGCOLOR
	BoxBorderColor $DARK
	BoxFontColor $DARK
	''
	DelayFontColor $DARK
	''
	LifeLineBorderColor $DARK
	LifeLineBackgroundColor $DARK
	''
	GroupBorderColor $DARK
	GroupFontColor $DARK
	GroupHeaderBackgroundColor $SECONDARY_BORDER
	GroupBackgroundColor $DARK
	GroupBodyBackgroundColor $BGCOLOR
	GroupHeaderFontColor $PRIMARY_TEXT
	GroupHeaderFontStyle bold
	''
	DividerBackgroundColor $SECONDARY
    DividerBorderColor $SECONDARY_BORDER
    DividerFontColor $SECONDARY_TEXT
	''
	ReferenceHeaderBackgroundColor $DARK
	ReferenceBorderColor $DARK
	ReferenceFontColor $DARK
	ReferenceHeaderFontColor $PRIMARY
	''
	StereotypeFontColor $PRIMARY_TEXT
}
!endsub

!startsub participant
skinparam participant {
	FontColor $INFO
	BackgroundColor $DARK
	BorderColor $DARK
}
!endsub

!startsub actor
skinparam actor {
	$outline_scheme()
}
!endsub

!startsub collections
skinparam collections {
	BackgroundColor $PRIMARY_TEXT
	BorderColor $DARK
}
!endsub

!startsub control
skinparam control {
	$outline_scheme()
}
!endsub

!startsub entity
skinparam entity {
	$outline_scheme()
}
!endsub

!startsub boundary
skinparam boundary {
	$outline_scheme()
}
!endsub

!startsub agent

skinparam agent {
	$outline_scheme()
}
!endsub

!startsub database

skinparam database {
	$outline_scheme()
}
!endsub

!startsub note

skinparam note {
	BackgroundColor  #fff4d1
	BorderColor  $DARK
	FontColor $DARK
}
!endsub

!startsub artifact

skinparam artifact {
	$outline_scheme()
}
!endsub

!startsub component

skinparam component {
	$outline_scheme()
	BackgroundColor $WHITE
}
!endsub

!startsub interface

skinparam interface {
	BackgroundColor  $BGCOLOR
	BorderColor  $DANGER
	FontColor $DARK
}
!endsub

!startsub storage

skinparam storage {
	$primary_scheme()
}
!endsub

!startsub node

skinparam node {
	$secondary_scheme()
}
!endsub

!startsub cloud

skinparam cloud {
	$outline_scheme()
}
!endsub


!startsub class

skinparam class {
	$primary_scheme()
	HeaderBackgroundColor $PRIMARY
	AttributeFontSize 11
	AttributeFontColor $PRIMARY_TEXT
	AttributeIconSize 14
}
!endsub

!startsub object

skinparam object {
	$primary_scheme()
	HeaderBackgroundColor $PRIMARY
	AttributeFontSize 11
	AttributeFontColor $PRIMARY_TEXT
}
!endsub

!startsub usecase

skinparam usecase {
	$primary_scheme()
}
!endsub

!startsub rectangle

skinparam rectangle {
	$outline_scheme()
}
!endsub

!startsub package

skinparam package {
	$secondary_scheme()
}
!endsub

!startsub folder

skinparam folder {
	$secondary_scheme()
}
!endsub

!startsub frame

skinparam frame {
	$secondary_scheme()
}
!endsub

!startsub queue

skinparam queue {
	$secondary_scheme()
}
!endsub

!startsub card

skinparam card {
	$primary_scheme()
}
!endsub

!startsub file

skinparam file {
	$primary_scheme()
}
!endsub

!startsub stack

skinparam stack {
	$outline_scheme()
}
!endsub

!startsub state

skinparam state {
	$secondary_scheme()
	StartColor $DARK
	EndColor $DARK
	AttributeFontColor $SECONDARY_TEXT
	AttributeFontSize 11
}
!endsub
